### ISSUE TITLE
OpenApi/ Make `Vec<bool>`'s default value `false` instead of `null`

### ISSUE THREAD

**Issue by zhiburt** [msrd0/gotham_restful#176]
Hi there once again,

Just noticed this behavior.

![image](https://user-images.githubusercontent.com/20165848/151347090-e6b567b2-9dcb-4664-9ff9-328d60ac0db2.png)

I could imagine the same can be applied to numbers.
And I could imagine it may not be easy to solve.

But I think it would be cool to use a real default value isn't it?

**Comment by msrd0** [comment]
I assume you are referring to the generated HTML documentation - which, when I return a `Vec<bool>` from an endpoint, renders this as the default value (note that this is just redoc's default behaviour, I don't specify this explicitly in the schema):

![image](https://user-images.githubusercontent.com/7853372/151354155-1716e565-4bf7-4354-baf8-c1072321f620.png)

**Comment by msrd0** [comment]
The same applies when you include it in the request:

![image](https://user-images.githubusercontent.com/7853372/151354801-a10ffc6c-dde3-4182-b096-5c59945b18e5.png)

**Comment by zhiburt** [comment]
> I assume you are referring to the generated HTML documentation

True

> which, when I return a Vec<bool> from an endpoint, renders this as the default value (note that this is just redoc's default behaviour, I don't specify this explicitly in the schema):

But that's exactly what I have but it turned to be different.

Could you include your vector in some other type?

Like this.
I intentionally made it a bit verbose, just in case.

```Rust
 #[derive(OpenapiType, Deserialize, Serialize)]
  struct Request {
      values: Vec<Value>,
  }

  #[derive(OpenapiType, Deserialize, Serialize)]
  struct Value {
      something: Something,
  }

  #[derive(OpenapiType, Deserialize, Serialize)]
  struct Something {
      list: Vec<bool>,
  }
```

**Comment by msrd0** [comment]
This looks exactly as expected:

![image](https://user-images.githubusercontent.com/7853372/151428012-edb060d1-f00a-475f-94b5-d218ee77b89d.png)

**Comment by zhiburt** [comment]
Could you try the following?

Once again it may be a little bit too verbose.

```Rust

    #[derive(OpenapiType, Deserialize, Serialize,Default)]
    struct A {
        fields: Vec<B>,
    }
    
    #[derive(OpenapiType, Deserialize, Serialize,Default)]
    struct B {
        fields: Vec<C>,
    }
    
    #[derive(OpenapiType, Deserialize, Serialize,Default)]
    struct C {
        fields: Vec<D>,
    }
    
    #[derive(OpenapiType, Deserialize, Serialize,Default)]
    struct D {
        #[serde(flatten)]
        fields: E,
    }
        
    #[derive(OpenapiType, Deserialize, Serialize,Default)]
    struct E {
        fields: Vec<F>,
    }

        
    #[derive(OpenapiType, Deserialize, Serialize, Default)]
    struct F {
        fields: Vec<bool>,
    }
    
    /// StrategyScoreResource an endpoint for score calculation
    #[derive(Resource)]
    #[resource(requst)]
    pub struct VehicleScoreResource;


    #[create]
    async fn requst(_: A) -> io::Result<A> {
        Ok(A::default())
    }
```

![image](https://user-images.githubusercontent.com/20165848/151520190-7db972a0-e1cb-4e66-9da1-4fd060c704de.png)

My guess it's related to `flatten`

**Comment by zhiburt** [comment]
Could you try the following?

Once again it may be a little bit too verbose.

```Rust

    #[derive(OpenapiType, Deserialize, Serialize,Default)]
    struct A {
        fields: Vec<B>,
    }
    
    #[derive(OpenapiType, Deserialize, Serialize,Default)]
    struct B {
        fields: Vec<C>,
    }
    
    #[derive(OpenapiType, Deserialize, Serialize,Default)]
    struct C {
        fields: Vec<D>,
    }
    
    #[derive(OpenapiType, Deserialize, Serialize,Default)]
    struct D {
        #[serde(flatten)]
        fields: E,
    }
        
    #[derive(OpenapiType, Deserialize, Serialize,Default)]
    struct E {
        fields: Vec<F>,
    }

        
    #[derive(OpenapiType, Deserialize, Serialize, Default)]
    struct F {
        fields: Vec<bool>,
    }
    
    #[derive(Resource)]
    #[resource(requst)]
    pub struct Resource;


    #[create]
    async fn requst(_: A) -> io::Result<A> {
        Ok(A::default())
    }
```

![image](https://user-images.githubusercontent.com/20165848/151520190-7db972a0-e1cb-4e66-9da1-4fd060c704de.png)

My guess it's related to `flatten`

**Comment by msrd0** [comment]
This is not related to `flatten`. You hit the maximum render depth of redoc. This is documented in their [readme](https://github.com/Redocly/redoc#redoc-options-object):

> - `generatedPayloadSamplesMaxDepth` - set the maximum render depth for JSON payload samples (responses and request body). The default value is `10`.

**Comment by zhiburt** [comment]
I see.

Sorry if I bothered you with not checking documentation first :sweat_smile: 

Then I I'll close it.

Thank you
